# Generated by Django 2.2.5 on 2020-01-09 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0002_auto_20180130_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2bTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=50, null=True)),
                ('TransID', models.CharField(blank=True, max_length=50, null=True)),
                ('TransTime', models.DateTimeField(blank=True, null=True)),
                ('TransAmount', models.CharField(blank=True, max_length=50, null=True)),
                ('BusinessShortCode', models.CharField(blank=True, max_length=50, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=50, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=50, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=50, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('ResultCode', models.IntegerField(blank=True, null=True)),
                ('ResultDesc', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance', models.CharField(default=0, max_length=12)),
                ('TranscationDate', models.DateTimeField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawPayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('referrals', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='referrals.Referral')),
                ('referrer', models.CharField(default='None', max_length=50)),
                ('referred', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('referrals_paid', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
