# Generated by Django 2.2.5 on 2020-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C2bTransaction',
        ),
        migrations.DeleteModel(
            name='LNMOnline',
        ),
    ]
