# Generated by Django 2.2.5 on 2020-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200110_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawpayouts',
            name='amount',
        ),
        migrations.AddField(
            model_name='withdrawpayouts',
            name='amount_dispensed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='withdrawpayouts',
            name='amount_request',
            field=models.FloatField(default=0.0),
        ),
    ]
